<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, ref, toRaw, watch } from 'vue';

type BackgroundTheme = 'spring-morning' | 'summer-noon' | 'autumn-evening' | 'winter-night';
type FormationPattern = 'auto' | 'v' | 'line' | 'echelon' | 'convoy' | 'custom';
type CustomEnemyKind = 'fighter' | 'bomber' | 'diveBomber' | 'interceptor';
type PowerUpKind = 'repair' | 'shield' | 'rapid' | 'spread' | 'laser' | 'plasma' | 'rocket';
type PowerUpWeights = Record<PowerUpKind, number>;
type GeneratorStyle = 'mixed' | 'air' | 'ground';
type Tab = 'level' | 'wave' | 'powerups';
interface CustomSlot { kind: CustomEnemyKind; col: number; row: number }
interface Wave { id: number; truckCount: number; fighterCount: number; bomberCount: number; diveBomberCount: number; tankCount: number; rocketTruckCount: number; interceptorCount: number; spawnInterval: number; enemySpeedScale: number; fireRateScale: number; formationChance: number; formationSize: number; formationPattern: FormationPattern; customFormation: CustomSlot[] }
interface Level { id: number; name: string; ringSpawnInterval: number; ringSpeed: number; ringRadius: number; ringRandomY: number; backgroundSpeed: number; backgroundTheme: BackgroundTheme; movingRingChance: number; shrinkingRingChance: number; powerUpChance: number; powerUpWeights: PowerUpWeights; targetScore: number; difficultyEvery: number; difficultySpeedStep: number; waves: Wave[] }

const themes: { id: BackgroundTheme; label: string; time: string }[] = [
  { id: 'spring-morning', label: '春季', time: '清晨' }, { id: 'summer-noon', label: '夏季', time: '正午' },
  { id: 'autumn-evening', label: '秋季', time: '傍晚' }, { id: 'winter-night', label: '冬季', time: '夜晚' },
];
const defaultWeights = (): PowerUpWeights => ({ repair: 2, shield: 2, rapid: 3, spread: 3, laser: 2, plasma: 2, rocket: 2 });
const wave = (id: number): Wave => ({ id, truckCount: 3, fighterCount: 4, bomberCount: 1, diveBomberCount: 1, tankCount: 1, rocketTruckCount: 0, interceptorCount: Math.max(0, id - 1), spawnInterval: 1.2, enemySpeedScale: 1, fireRateScale: 1, formationChance: .5, formationSize: 3, formationPattern: 'auto', customFormation: [] });
const enemyCount = (item: Wave) => item.formationPattern === 'custom' ? item.customFormation.length : item.truckCount + item.fighterCount + item.bomberCount + item.diveBomberCount + item.tankCount + item.rocketTruckCount + item.interceptorCount;
const seed: Level[] = [
  { id: 1, name: 'Level 1', ringSpawnInterval: 1.8, ringSpeed: 260, ringRadius: 92, ringRandomY: 220, backgroundSpeed: 45, backgroundTheme: 'spring-morning', movingRingChance: .12, shrinkingRingChance: .08, powerUpChance: .2, powerUpWeights: { repair: 3, shield: 3, rapid: 3, spread: 2, laser: 2, plasma: 1, rocket: 1 }, targetScore: 20, difficultyEvery: 5, difficultySpeedStep: 16, waves: [{ ...wave(1), fighterCount: 2, bomberCount: 0, formationChance: .35 }, { ...wave(2), formationPattern: 'v' }, { ...wave(3), truckCount: 5, fighterCount: 5, formationPattern: 'echelon', formationSize: 4, formationChance: .65 }] },
  { id: 2, name: 'Level 2', ringSpawnInterval: 1.45, ringSpeed: 310, ringRadius: 82, ringRandomY: 235, backgroundSpeed: 62, backgroundTheme: 'summer-noon', movingRingChance: .24, shrinkingRingChance: .16, powerUpChance: .17, powerUpWeights: defaultWeights(), targetScore: 30, difficultyEvery: 4, difficultySpeedStep: 20, waves: [{ ...wave(1), truckCount: 4, formationPattern: 'line' }, { ...wave(2), fighterCount: 6, formationPattern: 'v', formationSize: 4, formationChance: .65 }, { ...wave(3), truckCount: 6, fighterCount: 7, formationPattern: 'echelon', formationSize: 5, formationChance: .75 }] },
  { id: 3, name: 'Level 3', ringSpawnInterval: 1.15, ringSpeed: 360, ringRadius: 74, ringRandomY: 245, backgroundSpeed: 78, backgroundTheme: 'autumn-evening', movingRingChance: .3, shrinkingRingChance: .24, powerUpChance: .12, powerUpWeights: { repair: 1, shield: 2, rapid: 2, spread: 3, laser: 3, plasma: 3, rocket: 3 }, targetScore: 45, difficultyEvery: 3, difficultySpeedStep: 22, waves: [{ ...wave(1), truckCount: 5, fighterCount: 6, formationSize: 4, formationChance: .6 }, { ...wave(2), truckCount: 7, fighterCount: 8, formationPattern: 'v', formationSize: 5, formationChance: .75 }, { ...wave(3), truckCount: 8, fighterCount: 10, formationPattern: 'echelon', formationSize: 6, formationChance: .85 }] },
];
seed.push({ id: 4, name: 'Level 4', ringSpawnInterval: 1, ringSpeed: 395, ringRadius: 72, ringRandomY: 250, backgroundSpeed: 88, backgroundTheme: 'winter-night', movingRingChance: .35, shrinkingRingChance: .28, powerUpChance: .14, powerUpWeights: defaultWeights(), targetScore: 55, difficultyEvery: 3, difficultySpeedStep: 24, waves: [{ ...wave(1), fighterCount: 8, bomberCount: 2, interceptorCount: 3, formationPattern: 'v', formationSize: 5, formationChance: .75 }, { ...wave(2), truckCount: 6, fighterCount: 9, diveBomberCount: 4, interceptorCount: 4, formationPattern: 'echelon', formationSize: 6, formationChance: .85 }, { ...wave(3), truckCount: 7, fighterCount: 12, bomberCount: 3, diveBomberCount: 5, interceptorCount: 6, formationPattern: 'auto', formationSize: 6, formationChance: .9 }] });
const enemies = [
  ['truckCount', '防空卡车', 'AA'], ['fighterCount', '敌方战机', 'F'], ['bomberCount', '重型轰炸机', 'B'], ['diveBomberCount', '俯冲轰炸机', 'D'],
  ['tankCount', '重型坦克', 'T'], ['rocketTruckCount', '火箭发射车', 'R'], ['interceptorCount', '高速截击机', 'I'],
] as const;
const airEnemies: { id: CustomEnemyKind; label: string; glyph: string; color: string }[] = [
  { id: 'fighter', label: '战斗机', glyph: 'F', color: '#79d1ff' }, { id: 'bomber', label: '轰炸机', glyph: 'B', color: '#ffc168' },
  { id: 'diveBomber', label: '俯冲机', glyph: 'D', color: '#ff8d79' }, { id: 'interceptor', label: '截击机', glyph: 'I', color: '#be94ff' },
];
const formations: { id: FormationPattern; label: string; glyph: string; hint: string }[] = [
  { id: 'auto', label: '自动混合', glyph: '✦', hint: '每次随机选择空中编队' }, { id: 'v', label: 'V 字', glyph: '⌄', hint: '适合战机与轰炸机' },
  { id: 'line', label: '横排', glyph: '•••', hint: '同高度依次进入' }, { id: 'echelon', label: '梯队', glyph: '⁝', hint: '斜向依次进入' },
  { id: 'convoy', label: '车队', glyph: '▰▰', hint: '地面单位使用车队' }, { id: 'custom', label: '自定义', glyph: '▦', hint: '在有限棋盘上放置不同敌机' },
];
const powerUps: { id: PowerUpKind; label: string; icon: string; color: string }[] = [
  { id: 'repair', label: '修理', icon: '✚', color: '#77dca5' }, { id: 'shield', label: '护盾', icon: '◇', color: '#70c7ff' },
  { id: 'rapid', label: '高速射击', icon: '»', color: '#ffd25e' }, { id: 'spread', label: '散射', icon: '⋔', color: '#ff9b62' },
  { id: 'laser', label: '激光炮', icon: '━', color: '#54e9ff' }, { id: 'plasma', label: '等离子炮', icon: '●', color: '#ce83ff' }, { id: 'rocket', label: '火箭', icon: '➤', color: '#ff6b62' },
];

const levels = ref<Level[]>(structuredClone(seed)); const selectedId = ref(1); const selectedWaveId = ref(1); const tab = ref<Tab>('wave'); const mode = ref<'edit' | 'generate'>('edit');
const canvas = ref<HTMLCanvasElement>(); const toast = ref(''); const customTool = ref<CustomEnemyKind | 'erase'>('fighter'); const gridCells = Array.from({ length: 40 }, (_, index) => index);
const generator = reactive({ count: 5, waveMin: 2, waveMax: 5, enemyMin: 8, enemyMax: 22, difficultyStart: 1, difficultyStep: .18, style: 'mixed' as GeneratorStyle, replace: false, theme: 'random' as BackgroundTheme | 'random', powerUpMin: .08, powerUpMax: .22, powerUpWeights: defaultWeights() });
const current = computed(() => levels.value.find(item => item.id === selectedId.value) ?? levels.value[0]);
const selectedWave = computed(() => current.value.waves.find(item => item.id === selectedWaveId.value) ?? current.value.waves[0]);
const totalEnemies = computed(() => current.value.waves.reduce((sum, item) => sum + enemyCount(item), 0));
const weightTotal = computed(() => totalWeight(current.value.powerUpWeights)); const generatorWeightTotal = computed(() => totalWeight(generator.powerUpWeights));
const difficulty = computed(() => Math.round(current.value.waves.reduce((sum, item) => sum + enemyCount(item) * item.enemySpeedScale * item.fireRateScale / item.spawnInterval, 0)));
const errors = computed(() => { const result: string[] = []; if (current.value.powerUpChance < 0 || current.value.powerUpChance > 1) result.push('道具掉落概率必须在 0–1'); if (weightTotal.value <= 0) result.push('至少启用一种道具'); current.value.waves.forEach((item, index) => { if (enemyCount(item) < 1) result.push(`第 ${index + 1} 波没有敌人`); if (item.spawnInterval <= 0 || item.enemySpeedScale <= 0 || item.fireRateScale <= 0) result.push(`第 ${index + 1} 波参数必须大于 0`); if (item.formationPattern !== 'custom' && (item.formationChance < 0 || item.formationChance > 1 || item.formationSize < 2 || item.formationSize > 6)) result.push(`第 ${index + 1} 波编队参数无效`); }); return result; });

function totalWeight(weights: PowerUpWeights) { return Object.values(weights).reduce((sum, value) => sum + Math.max(0, value), 0); }
function chance(weights: PowerUpWeights, kind: PowerUpKind) { const total = totalWeight(weights); return total ? Math.round(weights[kind] / total * 100) : 0; }
function selectLevel(id: number) { selectedId.value = id; selectedWaveId.value = current.value.waves[0]?.id ?? 1; }
function selectWave(id: number) { selectedWaveId.value = id; tab.value = 'wave'; }
function addLevel() { const id = Math.max(0, ...levels.value.map(item => item.id)) + 1; levels.value.push({ ...structuredClone(toRaw(current.value)), id, name: `Level ${id}` }); selectLevel(id); }
function cloneLevel() { addLevel(); }
function removeLevel() { if (levels.value.length === 1) return flash('至少保留一个关卡'); const index = levels.value.findIndex(item => item.id === selectedId.value); levels.value.splice(index, 1); selectLevel(levels.value[Math.max(0, index - 1)].id); }
function addWave() { current.value.waves.push(wave(current.value.waves.length + 1)); selectWave(current.value.waves.length); }
function cloneWave(index: number) { current.value.waves.splice(index + 1, 0, structuredClone(toRaw(current.value.waves[index]))); renumberWaves(); selectedWaveId.value = index + 2; }
function removeWave(index: number) { if (current.value.waves.length === 1) return flash('至少保留一个波次'); current.value.waves.splice(index, 1); renumberWaves(); selectedWaveId.value = current.value.waves[Math.min(index, current.value.waves.length - 1)].id; }
function moveWave(index: number, offset: number) { const target = index + offset; if (target < 0 || target >= current.value.waves.length) return; const [item] = current.value.waves.splice(index, 1); current.value.waves.splice(target, 0, item); renumberWaves(); selectedWaveId.value = target + 1; }
function renumberWaves() { current.value.waves.forEach((item, index) => item.id = index + 1); }
function applyPreset(kind: GeneratorStyle) { const item = selectedWave.value; item.customFormation = []; if (kind === 'air') Object.assign(item, { truckCount: 0, fighterCount: 6, bomberCount: 2, diveBomberCount: 3, tankCount: 0, rocketTruckCount: 0, interceptorCount: 3, formationPattern: 'v', formationSize: 4 }); else if (kind === 'ground') Object.assign(item, { truckCount: 4, fighterCount: 0, bomberCount: 0, diveBomberCount: 0, tankCount: 3, rocketTruckCount: 2, interceptorCount: 0, formationPattern: 'convoy', formationSize: 3 }); else Object.assign(item, { truckCount: 3, fighterCount: 4, bomberCount: 1, diveBomberCount: 2, tankCount: 2, rocketTruckCount: 1, interceptorCount: 2, formationPattern: 'auto', formationSize: 3 }); flash('已套用编队预设'); }
function selectFormation(pattern: FormationPattern) { selectedWave.value.formationPattern = pattern; if (pattern === 'custom' && !selectedWave.value.customFormation.length) { selectedWave.value.customFormation = [{ kind: 'fighter', col: 2, row: 1 }, { kind: 'fighter', col: 1, row: 2 }, { kind: 'fighter', col: 2, row: 3 }]; syncCustomCounts(); } }
function customSlot(index: number) { const col = index % 8, row = Math.floor(index / 8); return selectedWave.value.customFormation.find(slot => slot.col === col && slot.row === row); }
function paintCustom(index: number) { const col = index % 8, row = Math.floor(index / 8); const slots = selectedWave.value.customFormation.filter(slot => slot.col !== col || slot.row !== row); if (customTool.value !== 'erase') slots.push({ kind: customTool.value, col, row }); selectedWave.value.customFormation = slots; syncCustomCounts(); }
function clearCustom() { selectedWave.value.customFormation = []; syncCustomCounts(); }
function syncCustomCounts() { const item = selectedWave.value; item.truckCount = item.tankCount = item.rocketTruckCount = 0; item.fighterCount = item.customFormation.filter(slot => slot.kind === 'fighter').length; item.bomberCount = item.customFormation.filter(slot => slot.kind === 'bomber').length; item.diveBomberCount = item.customFormation.filter(slot => slot.kind === 'diveBomber').length; item.interceptorCount = item.customFormation.filter(slot => slot.kind === 'interceptor').length; }
function randomInt(min: number, max: number) { const low = Math.ceil(Math.min(min, max)); return low + Math.floor(Math.random() * (Math.floor(Math.max(min, max)) - low + 1)); }
function randomFloat(min: number, max: number) { const low = Math.max(0, Math.min(1, Math.min(min, max))), high = Math.max(low, Math.min(1, Math.max(min, max))); return low + Math.random() * (high - low); }
function randomWave(id: number, levelDifficulty: number): Wave { const item = wave(id); const total = randomInt(generator.enemyMin, generator.enemyMax); const keys = generator.style === 'air' ? ['fighterCount', 'bomberCount', 'diveBomberCount', 'interceptorCount'] as const : generator.style === 'ground' ? ['truckCount', 'tankCount', 'rocketTruckCount'] as const : enemies.map(enemy => enemy[0]); for (const enemy of enemies) item[enemy[0]] = 0; for (let index = 0; index < total; index++) item[keys[randomInt(0, keys.length - 1)]]++; item.spawnInterval = Number(Math.max(.45, 1.55 - levelDifficulty * .15).toFixed(2)); item.enemySpeedScale = Number((.85 + levelDifficulty * .16).toFixed(2)); item.fireRateScale = Number((.8 + levelDifficulty * .18).toFixed(2)); item.formationChance = Number(Math.min(.95, .35 + levelDifficulty * .1).toFixed(2)); item.formationSize = Math.min(6, Math.max(2, 2 + Math.floor(levelDifficulty / 1.4))); item.formationPattern = generator.style === 'ground' ? 'convoy' : (['auto', 'v', 'line', 'echelon'] as FormationPattern[])[randomInt(0, 3)]; return item; }
function generateRandomLevels() { if (generatorWeightTotal.value <= 0) return flash('批量规则至少启用一种道具'); const amount = Math.max(1, Math.min(100, Math.floor(generator.count))); const minWaves = Math.max(1, Math.floor(Math.min(generator.waveMin, generator.waveMax))); const maxWaves = Math.max(minWaves, Math.floor(Math.max(generator.waveMin, generator.waveMax))); const firstId = generator.replace ? 1 : Math.max(0, ...levels.value.map(item => item.id)) + 1; const generated: Level[] = []; for (let index = 0; index < amount; index++) { const id = firstId + index, levelDifficulty = Math.max(.1, generator.difficultyStart + index * generator.difficultyStep), waveCount = randomInt(minWaves, maxWaves); generated.push({ ...structuredClone(seed[0]), id, name: `Level ${id}`, backgroundTheme: generator.theme === 'random' ? themes[randomInt(0, themes.length - 1)].id : generator.theme, ringSpeed: Math.round(230 + levelDifficulty * 45), backgroundSpeed: Math.round(35 + levelDifficulty * 9), targetScore: Math.round(15 + levelDifficulty * 8), difficultyEvery: Math.max(2, Math.round(6 - levelDifficulty)), difficultySpeedStep: Math.round(12 + levelDifficulty * 3), powerUpChance: Number(randomFloat(generator.powerUpMin, generator.powerUpMax).toFixed(2)), powerUpWeights: { ...generator.powerUpWeights }, waves: Array.from({ length: waveCount }, (_, waveIndex) => randomWave(waveIndex + 1, levelDifficulty + waveIndex * .16)) }); } if (generator.replace) levels.value = generated; else levels.value.push(...generated); selectLevel(generated[0].id); mode.value = 'edit'; flash(`已生成 ${amount} 个关卡，道具和地图均使用批量规则`); }
function exportJson() { if (errors.value.length) return flash('请先修复当前关卡配置错误'); const blob = new Blob([JSON.stringify({ levels: levels.value.map(level => ({ ...level, name: `Level ${level.id}` })) }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'levels.json'; link.click(); URL.revokeObjectURL(link.href); flash('已导出 levels.json'); }
function importJson(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)) as { levels: Partial<Level>[] }; if (!Array.isArray(parsed.levels) || !parsed.levels.length) throw new Error(); levels.value = parsed.levels.map((item, index) => { const id = item.id ?? index + 1; return { ...structuredClone(seed[0]), ...item, id, name: `Level ${id}`, backgroundTheme: item.backgroundTheme ?? 'spring-morning', powerUpWeights: { ...defaultWeights(), ...item.powerUpWeights }, waves: item.waves?.length ? item.waves.map((entry, waveIndex) => ({ ...wave(waveIndex + 1), ...entry, id: waveIndex + 1, customFormation: entry.customFormation ?? [] })) : [wave(1)] }; }); selectLevel(levels.value[0].id); flash(`已导入 ${levels.value.length} 个关卡`); } catch { flash('JSON 格式无效'); } }; reader.readAsText(file); (event.target as HTMLInputElement).value = ''; }
function flash(message: string) { toast.value = message; window.setTimeout(() => { if (toast.value === message) toast.value = ''; }, 2400); }

function draw() { const el = canvas.value, item = selectedWave.value; if (!el || !item) return; const ctx = el.getContext('2d'); if (!ctx) return; const ratio = devicePixelRatio, width = el.clientWidth, height = el.clientHeight; el.width = width * ratio; el.height = height * ratio; ctx.scale(ratio, ratio); ctx.imageSmoothingEnabled = false; const colors: Record<BackgroundTheme, [string, string, string]> = { 'spring-morning': ['#8ec8ef', '#f8d7aa', '#73905b'], 'summer-noon': ['#1689df', '#9bdafb', '#47743d'], 'autumn-evening': ['#9d3040', '#ff9b3d', '#765038'], 'winter-night': ['#071a42', '#244779', '#b7d7ef'] }; const palette = colors[current.value.backgroundTheme]; const sky = ctx.createLinearGradient(0, 0, 0, height); sky.addColorStop(0, palette[0]); sky.addColorStop(1, palette[1]); ctx.fillStyle = sky; ctx.fillRect(0, 0, width, height); ctx.fillStyle = palette[2]; ctx.fillRect(0, height - 55, width, 55); if (item.formationPattern === 'custom') { for (const slot of item.customFormation) drawEnemy(ctx, width * .48 + slot.col * 48, 42 + slot.row * 48, slot.kind); } else { const count = Math.min(6, item.formationSize), baseX = width * .62, baseY = height * .42, pattern = item.formationPattern === 'auto' ? 'v' : item.formationPattern; for (let i = 0; i < count; i++) { const slot = i - (count - 1) / 2, x = pattern === 'v' ? baseX + Math.abs(slot) * 48 : baseX + i * 58, y = pattern === 'convoy' ? height - 57 : baseY + (pattern === 'v' ? slot * 38 : pattern === 'echelon' ? slot * 30 : 0); drawEnemy(ctx, x, y, pattern === 'convoy' ? 'bomber' : i % 2 ? 'fighter' : 'interceptor'); } } ctx.fillStyle = '#ffffffcc'; ctx.font = '12px sans-serif'; ctx.fillText(`${themes.find(theme => theme.id === current.value.backgroundTheme)?.label}${themes.find(theme => theme.id === current.value.backgroundTheme)?.time} · ${formations.find(entry => entry.id === item.formationPattern)?.label}`, 16, height - 14); }
function drawEnemy(ctx: CanvasRenderingContext2D, x: number, y: number, kind: CustomEnemyKind) { const data = airEnemies.find(item => item.id === kind)!; ctx.fillStyle = data.color; ctx.fillRect(x - 22, y - 5, 44, 10); ctx.fillRect(x - 3, y - 13, 16, 26); ctx.fillStyle = '#101827'; ctx.font = 'bold 10px sans-serif'; ctx.fillText(data.glyph, x - 3, y + 4); }
watch(levels, () => nextTick(draw), { deep: true }); watch([selectedId, selectedWaveId], () => nextTick(draw)); onMounted(() => { draw(); new ResizeObserver(draw).observe(canvas.value!); });
</script>

<template>
  <main class="shell">
    <header class="topbar"><div><p class="eyebrow">MISSILE AVIATOR</p><h1>战斗关卡编辑器</h1></div><nav class="mode-switch"><button :class="{ active: mode === 'edit' }" @click="mode = 'edit'">编辑已有/单个关卡</button><button :class="{ active: mode === 'generate' }" @click="mode = 'generate'">批量生成新关卡</button></nav><div class="actions"><label class="button ghost">导入 JSON<input type="file" accept="application/json" @change="importJson"></label><button class="button primary" @click="exportJson">导出关卡</button></div></header>
    <section v-if="mode === 'generate'" class="batch-workspace"><header><div><p class="eyebrow">BATCH RULES</p><h2>批量生成新关卡</h2></div><strong>这里的设置只作用于接下来生成的新关卡，不会修改任何已有或当前选中的关卡。</strong></header><div class="batch-columns">
      <section class="panel batch-panel"><h3>① 数量和难度</h3><div class="field-grid"><label>关卡数量<input v-model.number="generator.count" type="number" min="1" max="100"></label><label>生成方式<select v-model="generator.replace"><option :value="false">追加到现有关卡</option><option :value="true">覆盖全部关卡</option></select></label><label>最少波次<input v-model.number="generator.waveMin" type="number" min="1"></label><label>最多波次<input v-model.number="generator.waveMax" type="number" min="1"></label><label>每波最少敌人<input v-model.number="generator.enemyMin" type="number" min="1"></label><label>每波最多敌人<input v-model.number="generator.enemyMax" type="number" min="1"></label><label>起始难度<input v-model.number="generator.difficultyStart" type="number" min="0.1" step="0.1"></label><label>每关难度递增<input v-model.number="generator.difficultyStep" type="number" min="0" step="0.01"></label></div><label class="wide-field">部队规则<select v-model="generator.style"><option value="mixed">空地混合</option><option value="air">纯空战</option><option value="ground">地面部队</option></select></label></section>
      <section class="panel batch-panel"><h3>② 季节与时间</h3><p class="help">选择“随机”时，每个生成的关卡都会独立抽取一种地图。</p><label class="wide-field">地图生成规则<select v-model="generator.theme"><option value="random">随机四套地图</option><option v-for="theme in themes" :key="theme.id" :value="theme.id">{{ theme.label }} · {{ theme.time }}</option></select></label><div class="theme-grid"><button v-for="theme in themes" :key="theme.id" :class="['theme-card', theme.id, { active: generator.theme === theme.id }]" @click="generator.theme = theme.id"><b>{{ theme.label }}</b><span>{{ theme.time }}</span></button></div></section>
      <section class="panel batch-panel"><h3>③ 批量关卡的道具规则</h3><p class="help strong-help">只控制新生成的关卡。每个新关卡会在最低和最高掉落率之间随机取值。</p><div class="field-grid"><label>最低掉落率<input v-model.number="generator.powerUpMin" type="number" min="0" max="1" step="0.01"></label><label>最高掉落率<input v-model.number="generator.powerUpMax" type="number" min="0" max="1" step="0.01"></label></div><div class="power-list batch-power"><label v-for="item in powerUps" :key="item.id"><i :style="{ color: item.color, borderColor: item.color }">{{ item.icon }}</i><span><b>{{ item.label }}</b><small>{{ chance(generator.powerUpWeights, item.id) }}%</small></span><input v-model.number="generator.powerUpWeights[item.id]" type="number" min="0" max="20"></label></div><small class="hint">权重为 0 表示批量生成的关卡不会掉落该道具。</small></section>
    </div><button class="button primary batch-generate" @click="generateRandomLevels">按以上三组规则生成 {{ generator.count }} 个关卡</button></section>
    <section v-else class="workspace"><aside class="panel level-list"><div class="section-title"><span>已有的关卡</span><button title="新增关卡" @click="addLevel">＋</button></div><button v-for="level in levels" :key="level.id" class="level-card" :class="{ active: level.id === selectedId }" @click="selectLevel(level.id)"><span class="level-number">{{ String(level.id).padStart(2, '0') }}</span><span><b>Level {{ level.id }}</b><small>{{ themes.find(theme => theme.id === level.backgroundTheme)?.label }}{{ themes.find(theme => theme.id === level.backgroundTheme)?.time }} · {{ level.waves.length }} 波</small></span></button><div class="list-actions"><button @click="cloneLevel">复制</button><button class="danger" @click="removeLevel">删除</button></div></aside>
      <section class="center"><div class="preview-card"><div class="card-head"><span>LEVEL {{ current.id }} · WAVE {{ selectedWave.id }} 预览</span><span class="badge">难度 {{ difficulty }}</span></div><canvas ref="canvas"></canvas><div class="metrics"><span><b>{{ current.waves.length }}</b> 波次</span><span><b>{{ totalEnemies }}</b> 敌人</span><span><b>{{ Math.round(current.powerUpChance * 100) }}%</b> 当前关卡掉落率</span><span><b>{{ current.targetScore }}</b> 目标分</span></div></div><div class="wave-toolbar"><b>波次时间线</b><button @click="addWave">＋ 新波次</button></div><div class="wave-list"><article v-for="(item, index) in current.waves" :key="item.id" class="wave-summary" :class="{ active: item.id === selectedWaveId }" @click="selectWave(item.id)"><div><b>W{{ item.id }}</b><span>{{ formations.find(entry => entry.id === item.formationPattern)?.label }}</span></div><strong>{{ enemyCount(item) }}</strong><small>敌人</small><footer><button @click.stop="moveWave(index, -1)">↑</button><button @click.stop="moveWave(index, 1)">↓</button><button @click.stop="cloneWave(index)">⧉</button><button @click.stop="removeWave(index)">×</button></footer></article></div><div v-if="errors.length" class="errors"><b>当前关卡需要调整</b><span v-for="error in errors" :key="error">{{ error }}</span></div><div v-else class="valid">✓ 当前关卡配置有效</div></section>
      <aside class="panel inspector"><nav class="tabs"><button :class="{ active: tab === 'level' }" @click="tab = 'level'">当前关卡</button><button :class="{ active: tab === 'wave' }" @click="tab = 'wave'">当前波次</button><button :class="{ active: tab === 'powerups' }" @click="tab = 'powerups'">当前关卡道具</button></nav>
        <section v-if="tab === 'level'" class="tab-content"><h2>正在编辑：Level {{ current.id }}</h2><label class="wide-field">本关地图<select v-model="current.backgroundTheme"><option v-for="theme in themes" :key="theme.id" :value="theme.id">{{ theme.label }} · {{ theme.time }}</option></select></label><div class="field-grid"><label>场景速度<input v-model.number="current.ringSpeed" type="number" min="120"></label><label>背景速度<input v-model.number="current.backgroundSpeed" type="number" min="0"></label><label>目标分数<input v-model.number="current.targetScore" type="number" min="1"></label><label>难度间隔<input v-model.number="current.difficultyEvery" type="number" min="1"></label></div></section>
        <section v-else-if="tab === 'wave'" class="tab-content"><h2>正在编辑：WAVE {{ selectedWave.id }} <small>{{ enemyCount(selectedWave) }} 敌人</small></h2><div class="presets"><button @click="applyPreset('air')">空中突击</button><button @click="applyPreset('mixed')">混合部队</button><button @click="applyPreset('ground')">地面车队</button></div><h3>编队样式</h3><div class="formation-grid"><button v-for="formation in formations" :key="formation.id" :class="{ active: selectedWave.formationPattern === formation.id }" :title="formation.hint" @click="selectFormation(formation.id)"><b>{{ formation.glyph }}</b><span>{{ formation.label }}</span></button></div>
          <template v-if="selectedWave.formationPattern === 'custom'"><div class="custom-head"><div><h3>自定义敌机棋盘</h3><p>固定 8 × 5，先选敌机类型，再点击格子放置。</p></div><button @click="clearCustom">清空棋盘</button></div><div class="enemy-tools"><button v-for="enemy in airEnemies" :key="enemy.id" :class="{ active: customTool === enemy.id }" :style="{ '--enemy': enemy.color }" @click="customTool = enemy.id"><b>{{ enemy.glyph }}</b>{{ enemy.label }}</button><button :class="{ active: customTool === 'erase' }" @click="customTool = 'erase'"><b>×</b>橡皮擦</button></div><div class="formation-board"><button v-for="cell in gridCells" :key="cell" :class="{ filled: customSlot(cell) }" :style="{ '--enemy': airEnemies.find(enemy => enemy.id === customSlot(cell)?.kind)?.color }" @click="paintCustom(cell)"><span v-if="customSlot(cell)">{{ airEnemies.find(enemy => enemy.id === customSlot(cell)?.kind)?.glyph }}</span></button></div><p class="board-help">左侧格子先进入屏幕；同一列保持相同前后位置。棋盘就是本波完整敌机列表。</p></template>
          <template v-else><h3>敌人组成</h3><div class="enemy-grid"><label v-for="enemy in enemies" :key="enemy[0]"><i>{{ enemy[2] }}</i><span>{{ enemy[1] }}</span><input v-model.number="selectedWave[enemy[0]]" type="number" min="0" max="99"></label></div><label class="slider-field"><span>编队出现概率 <b>{{ Math.round(selectedWave.formationChance * 100) }}%</b></span><input v-model.number="selectedWave.formationChance" type="range" min="0" max="1" step="0.05"></label><label class="slider-field"><span>每组规模 <b>{{ selectedWave.formationSize }} 架/辆</b></span><input v-model.number="selectedWave.formationSize" type="range" min="2" max="6" step="1"></label></template><div class="field-grid"><label>生成间隔<input v-model.number="selectedWave.spawnInterval" type="number" min="0.1" step="0.05"></label><label>移动倍率<input v-model.number="selectedWave.enemySpeedScale" type="number" min="0.1" step="0.05"></label><label>射速倍率<input v-model.number="selectedWave.fireRateScale" type="number" min="0.1" step="0.05"></label></div></section>
        <section v-else class="tab-content"><h2>当前：Level {{ current.id }} 的道具</h2><p class="help strong-help">这里只修改当前选中的 Level {{ current.id }}，不会影响批量生成规则或其他关卡。</p><label class="slider-field power-rate"><span>本关总体掉落率 <b>{{ Math.round(current.powerUpChance * 100) }}%</b></span><input v-model.number="current.powerUpChance" type="range" min="0" max="0.5" step="0.01"></label><div class="power-list"><label v-for="item in powerUps" :key="item.id"><i :style="{ color: item.color, borderColor: item.color }">{{ item.icon }}</i><span><b>{{ item.label }}</b><small>{{ chance(current.powerUpWeights, item.id) }}%</small></span><input v-model.number="current.powerUpWeights[item.id]" type="number" min="0" max="20"></label></div><small class="hint">先按本关总体掉落率判断是否掉落，再按权重决定道具类型。权重 0 表示本关不掉落该类型。</small></section>
      </aside></section><div v-if="toast" class="toast">{{ toast }}</div>
  </main>
</template>
